[default_config]
# Configure documentation available for features like hover and completions
assembler = "nasm"
instruction_set = "x86/x86-64"

# [opts]
# # The `compiler` field is the name of a compiler/assembler on your path
# # (or the absolute path to the file) that is used to build your source files
# # This program will be used to generate diagnostics
# compiler = "zig" # need "cc" as the first argument in `compile_flags.txt`
# diagnostics = true
# default_diagnostics = true
