version : "3.8"

services:
  mariadb:
    container_name: mariadb
    build: ./mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      wordpress:
        aliases:
          - $DBHOST 
    expose:
      - "3306:3306"
    restart: always 
  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
    restart: always
    build: ./wordpress/
    env_file:
      - .env
    expose:
      - "9000:80"
    volumes:
      - wordpress_data:/var/www/html/
    networks:
      wordpress:
        aliases:
          - $WPHOST
  nginx:
    container_name : nginx
    image: nginx
    volumes:
      - wordpress_data:/var/www/html
    depends_on :
      - wordpress
    networks:
      wordpress:
        aliases:
          - $WPHOST
    ports:
      - "8080:8080"
    expose:
      - "8080:8080"
    restart: always
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device : $HOME/data/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: $HOME/data/wordpress
      o: bind
networks:
  wordpress:
    name: wordpress
    driver: bridge

