version : "3.8"

services:
  mariadb:
    container_name: mariadb
    build: ./mariadb
    env_file:
      - .env
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      wordpress:
        aliases:
          - $DBHOST 
    expose:
      - "3306:3306"
    restart: always 
  wordpress:
    container_name: wordpress
    depends_on:
      - mariadb
      - redis
    restart: always
    build: ./wordpress/
    env_file:
      - .env
    expose:
      - "9000:80"
    volumes:
      - wordpress_data:/var/www/html/
    networks:
      wordpress:
        aliases:
          - $WPHOST
  nginx:
    container_name : nginx
    build: ./nginx/
    depends_on:
      - wordpress
      - adminer
      - python_blog
    volumes:
      - wordpress_data:/var/www/html
    depends_on :
      - wordpress
    env_file:
      - .env
    networks:
      wordpress:
        aliases:
          - nginx
    ports:
      - "443:443"
    expose:
      - "443:443"
    restart: always
  redis:
    container_name: redis
    restart: always
    build: ./bonus/redis
    env_file:
      - .env
    networks:
      wordpress:
        aliases:
          - redis
    volumes:
      - wordpress_data:/var/www/html/
    expose:
      - "6379:6379"
  adminer:
    container_name: adminer
    depends_on:
      - mariadb
    restart: always
    build: ./bonus/adminer/
    env_file:
      - .env
    networks:
      wordpress:
        aliases:
          - adminer
    expose:
      - "81:81"
    volumes:
      - wordpress_data:/var/www/html/
  python_blog:
    container_name: python_blog
    restart: always
    build: ./bonus/python_blog/
    env_file: .env
    ports:
      - "80:80"
    networks:
      wordpress:
        aliases:
          - python_blog
    volumes:
      - python_blog_data:/database/
volumes:
  mariadb_data:
    driver: local
    driver_opts:
      type: none
      device : $HOME/data/mysql
      o: bind
  wordpress_data:
    driver: local
    driver_opts:
      type: none
      device: $HOME/data/wordpress
      o: bind
  python_blog_data:
    driver: local
    driver_opts:
      type: none
      device: $HOME/data/python_blog_data
      o: bind
networks:
  wordpress:
    name: wordpress
    driver: bridge

